### ISSUE TITLE
Dialyzer complaining about broken contract.

### ISSUE THREAD

**Issue by KaranAhlawat** [shiryel/rayex#8]
In the following code snippet

```elixir
  def main_loop() do
    Rayex.Core.clear_background(%Color{r: 255, g: 255, b: 255, a: 255})

    Rayex.Core.begin_drawing()

    Rayex.Shapes.draw_triangle(
      %Vector2{x: @screen_width / 4.0 * 3.0, y: 80.0},
      %Vector2{x: @screen_width / 4.0 * 3.0 - 60.0, y: 150.0},
      %Vector2{x: @screen_width / 4.0 * 3.0 + 60.0, y: 150.0},
      %Color{r: 128, g: 0, b: 128, a: 255}
    )

    Rayex.Core.end_drawing()
    main_loop()
  end
```

Dialyzer complains when i pass in 0 as the value for `g` in the `Rayex.Structs.Color` struct. I believe the cause is that it expects a positive integer, which 0 is not.
The warning goes away once i pass in any integer above 0.

Any ideas how i can go about using 0 without the dialyzer complaining?

**Comment by shiryel** [comment]
Thanks for pointing that issue out, hopefully this commit fix that for you (and also many other cases that I missed before) :smile:

Also, just a heads-up, if you find any problem or want to extend the lib feel free to do so, current this lib only implements 20% of the [raylib cheatsheet](https://www.raylib.com/cheatsheet/cheatsheet.html)

Have fun :heart:

**Comment by shiryel** [comment]
Version 0.0.2 up, please update your deps :+1:

**Comment by KaranAhlawat** [comment]
Hey, thanks for the quick action. I was thinking of making a PR myself, after discussing with you when you responded. But since you've already done that, I'll be closing the issue. Thank you for your work!
